# Generated by Django 5.1.6 on 2025-02-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glapped_main', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
