# Generated by Django 5.1.6 on 2025-02-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Glapped_main", "0003_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="resources/default.jpg", upload_to="product_images"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
