# Generated by Django 5.1.6 on 2025-02-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glapped_main', '0004_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
