# Generated by Django 5.1.6 on 2025-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glapped_main', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='resources/default.jpg', upload_to='product_images'),
        ),
    ]
