# Generated by Django 5.1.6 on 2025-02-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Glapped_main", "0009_product_buyer_product_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
    ]
