# Generated by Django 5.1.6 on 2025-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Glapped_main", "0010_remove_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="Product", max_length=255),
        ),
    ]
