# Generated by Django 5.1.6 on 2025-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glapped_main', '0014_rename_current_bid_auctionproduct_current_highest_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
