# Generated by Django 5.1.6 on 2025-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glapped_main', '0016_auctionproduct_auction_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='starting_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
