# Generated by Django 5.1.6 on 2025-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glapped_main', '0017_alter_auctionproduct_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='auction_length',
            field=models.PositiveIntegerField(),
        ),
    ]
